### ISSUE TITLE
MissingReferenceException: The variable Sheet of TownTileMap doesn't exist anymore.

### ISSUE THREAD

**Issue by gkjolin** [rakkarage/RageTileMap#2]
This can't work on unity 5.6, could you update this project to unity5.6 or higher version?

MissingReferenceException: The variable Sheet of TownTileMap doesn't exist anymore.
You probably need to reassign the Sheet variable of the 'TownTileMap' script in the inspector.
ca.HenrySoftware.Rage.TileMap.SetTile (Int32 layer, Int32 index, Int32 tile, TileFlags flags, Boolean commit, Boolean find) (at Assets/RageTileMap/Rage/TileMap.cs:317)
ca.HenrySoftware.Rage.TileMap.Load () (at Assets/RageTileMap/Rage/TileMap.cs:232)
ca.HenrySoftware.Rage.TileMap.LoadJson (System.String text) (at Assets/RageTileMap/Rage/TileMap.cs:185)
TownTileMap.Start () (at Assets/RageTileMap/TownTileMap.cs:3512)

NullReferenceException: Object reference not set to an instance of an object
TownTileMap.Start () (at Assets/RageTileMap/TownTileMap.cs:3522)

var c = Manager.Instance.Character.transform.localPosition;

**Comment by rakkarage** [comment]
well the town art is sold separately as PixelLevel...
https://henrysoftware.itch.io/pixel-level
you can just drop in that png file and it should work, i included the Level.png.meta file with a guid

and i fixed the free one works too now

thanks
